config/routes.rb
Rails.application.routes.draw do
  resources :relationships
  resources :tweets
  resources :sessions
  resources :users

  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'buddies', to: 'users#buddies', as: 'buddies'

  root 'users#new'

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

	belongs_to :follower, class_name: 'User'
	belongs_to :followed, class_name: 'User'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	default_scope { order(created_at: :desc) }

	belongs_to :user

	validates :content, length: { maximum: 140 }
end

app/models/user.rb
require 'digest/md5'

class User < ActiveRecord::Base

has_many :tweets

has_many :follower_relationships, class_name: 'Relationship', foreign_key: 'followed_id'
has_many :followed_relationships, class_name: 'Relationship', foreign_key: 'follower_id'
has_many :followers, through: :follower_relationships
has_many :followeds, through: :followed_relationships

before_validation :prep_email
before_save :create_avatar_url

has_secure_password

validates :email, uniqueness: true, presence: true, format: { with: /\A[\w\.+-]+@([\w]+\.)+\w+\z/ }
validates :username, uniqueness: true, presence: true
validates :name, presence: true

def following? user
  self.followeds.include? user
end

def follow user
  Relationship.create follower_id: self.id, followed_id: user.id
end

private

def prep_email
  self.email = self.email.strip.downcase if self.email
end

def create_avatar_url
  self.avatar_url = "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(self.email)}?s=50"
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    relationship = Relationship.new(relationship_params)
    relationship.follower = current_user
    # The above is same as @relationship.follower_id = current_user.id 

    flash[:error] = "Couldn't follow" unless relationship.save
    redirect_to relationship.followed
  end

  def destroy
  	relationship = Relationship.find(params[:id])
  	user = relationship.followed
  	relationship.destroy
  	redirect_to user
  end

private

  def relationship_params
    params.require(:relationship).permit(:followed_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
  	user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash[:error] = "Wrong Username or Password"
      redirect_to root_url
    end
  end

  def destroy
  	session[:user_id] = nil
    redirect_to root_url, notice: "Logged Out"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
  end
  

  def create
    tweet = Tweet.new(tweet_params)
    tweet.user_id = current_user.id

    flash[:error] = "Your Tweet was over 140 characters" unless tweet.save
    redirect_to root_url 
       
  end

  private

  def tweet_params
    params.require(:tweet).permit(:content)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
	if current_user
		redirect_to buddies_path
	else
		@user = User.new
	end
end

def create
	@user = User.new(user_params)
	if @user.save
		session[:user_id] = @user.id
		redirect_to @user, notice: "Thank you for signing up for Twitter!"
	else
		render 'new'
	end
end

def show
	@user = User.find(params[:id])
	@tweet = Tweet.new
	@relationship = Relationship.where(
	  follower_id: current_user.id,
      followed_id: @user.id
    ).first_or_initialize if current_user
end

def index
	@users = User.all
	@tweet = Tweet.new
end

def buddies
    if current_user
      @tweet = Tweet.new
      buddies_ids = current_user.followeds.map(&:id).push(current_user.id)
      @tweets = Tweet.where(user_id: buddies_ids)
    else
      redirect_to root_url
    end
  end

def edit
	@user = User.find(params[:id])

	redirect_to @user unless @user == current_user
end

def update
	@user = User.find(params[:id])

	if @user.update_attributes(user_params)
		redirect_to @user, notice: "Profile updated!"
	else
		render 'edit'
	end
end

private

def user_params
  params.require(:user).permit(:email, :name, :username, :password, 
  	:password_confirmation, :bio)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  
  <link rel="stylesheet/less" href="/style.less">
  <script src="/less.js"></script>
  
  <%= csrf_meta_tags %>

</head>


<body>
	<header>
		<div class="wrapper">
			<img src="/gfx/logo.png">
			<% if current_user %>
            <%= link_to "Buddies' Tweets", buddies_path %>
            |
            <%= link_to "Public Tweets", tweets_path %>
            |
            <%= link_to "Public Profiles", users_path %>
            |
            <%= link_to "My Profile", current_user %>
            |
      			<%= link_to "Log Out", logout_path %>
      		<% else %>
        		<%= form_tag sessions_path do %>
          		<%= text_field_tag :username, nil, placeholder: "username" %>
          		<%= password_field_tag :password, nil,  placeholder: "password" %>
          		<%= submit_tag "Log In" %>
        		<% end %>
      		<% end %>
        </div>
    </header>

<div id="content">
	<div class="wrapper">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: "flash #{name}" %>
      <% end %>

	  <%= yield %>
	</div>
</div>

<footer>
	<div class="wrapper">
	Twitter - A micro blogging platform
	</div>
</footer>

</body>
</html>

app/views/tweets/index.html.erb
<% if current_user %>
    <%= render 'tweets/new_form' %>
<% end %>
<div class="panel left">
    <h1>Public Tweets</h1>
    <% @tweets.each do |tweet| %>
        <div class="tweetWrapper">
            <a href="<%= user_path tweet.user %>">
            <img class="avatar" src="<%= tweet.user.avatar_url %>">
            <span class="name"><%= tweet.user.name %></span> 
            </a>
            @<%= tweet.user.username %> 
            <span class="time"><%= time_ago_in_words(tweet.created_at) %></span>
            <p> <%= tweet.content %> </p>
        </div>
    <% end %>
</div>

<%= javascript_include_tag 'tweets' %>

app/views/users/buddies.html.erb
<% if current_user %>
    <%= render 'tweets/new_form' %>
<% end %>
<div class="panel left">
    <h1>Buddies' Tweets</h1>
    <% @tweets.each do |tweet| %>
        <div class="tweetWrapper">
            <a href="<%= user_path tweet.user %>">
            <img class="avatar" src="<%= tweet.user.avatar_url %>">
            <span class="name"><%= tweet.user.name %></span> 
            </a>
            @<%= tweet.user.username %> 
            <span class="time"><%= time_ago_in_words(tweet.created_at) %></span>
            <p> <%= tweet.content %> </p>
        </div>
    <% end %>
</div>

<%= javascript_include_tag 'tweets' %>

app/views/users/edit.html.erb
<div class="panel left">
  <h1>Edit Profile</h1>

    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <ul>
          <% @user.errors.full_messages.each do |e| %>
            <li><%= e %></li>
          <% end %>
        </ul>
      <% end %>

      </br>
      Email:</br>
      <%= f.text_field :email %>
      </br>
      </br>
      Name:</br> 
      <%= f.text_field :name %>
      </br>
      </br>
      Password:</br> 
      <%= f.password_field :password %>
      </br>
      </br>
      Password Confirmation:</br> 
      <%= f.password_field :password_confirmation %>
      </br>
      </br>
      Bio:</br> 
      <%= f.text_area :bio, cols:40, rows:5 %>
      </br>
      </br>
      <%= f.submit "Update" %>

    <% end %>
  </p>
</div>

app/views/users/index.html.erb
<% if current_user %>
    <%= render 'tweets/new_form' %>
<% end %>

<div class="panel left">
    <h1>Public Profiles</h1>
    <% @users.each do |user| %>
    <div class="tweetWrapper">
    	<a href="<%= user_path user %>">
        	<img class="avatar" src="<%= user.avatar_url %>">
        	<span class="name"><%= user.name %></span> 
        </a>
        @<%= user.username %>
        <p>
        <%= user.tweets.length %> Tweets
        <span class="spacing"><%= user.followers.length %> Followers</span>
        <span class="spacing"><%= user.followeds.length %> Following</span>
        </p>

        <% if user.bio %>
        	<p><%= user.bio %></p>
        <% elsif user.tweets.first %>
        	<p><%= user.tweets.first.content %></p>
        <% end %>

    </div>
    <% end %>
</div>

<%= javascript_include_tag 'tweets' %>

app/views/users/new.html.erb
<div class="panel right">
  <h1>New to Twitter?</h1>
  <p>
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <ul>
          <% @user.errors.full_messages.each do |e| %>
            <li><%= e %></li>
          <% end %>
        </ul>
      <% end %>

      <%= f.text_field :email, placeholder: "email" %>
      <%= f.text_field :username, placeholder: "username" %>
      <%= f.text_field :name, placeholder: "name" %>
      <%= f.password_field :password, placeholder: "password" %>
      <%= f.password_field :password_confirmation, placeholder: "password" %>
      <%= f.submit "Create account" %>
    <% end %>
  </p>
</div>

app/views/users/show.html.erb
<% if current_user %>
    <%= render 'tweets/new_form' %>
<% end %>

<div id="tweets" class="panel left">
    <h1>Twitter Profile
        <%= link_to("(edit profile)", edit_user_path(@user)) if @user == current_user %>
    </h1>
    <div class="tweetWrapper">
        <img class="avatar" src="<%= @user.avatar_url %>">
        <span class="name"><%= @user.name %></span> @<%= @user.username %>
        <p>
        <%= @user.tweets.length %> Tweets
        <span class="spacing"><%= @user.followers.length %> Followers</span>
        <span class="spacing"><%= @user.followeds.length %> Following</span>

        <% if @user.bio %>
            <p><%= @user.bio %></p>  
        <% end %>

        <% if current_user and @user != current_user %>
            <% if current_user.following? @user %>
                <%= form_tag @relationship, method: :delete do |f| %>
                <%= submit_tag "Unfollow" %>
                <% end %>
            
            <% else %>
                <%= form_for @relationship do |f| %>
                <%= f.hidden_field :followed_id, value: @user.id %>
                <%= submit_tag "Follow" %>
                <% end %>
            <% end %>
        <% end %>

        </p>
    </div>
</div>

<div class="panel left">
    <h1>Tweets</h1>

    <% @user.tweets.each do |tweet| %>
        <div class="tweetWrapper"> 
            <img class="avatar" src="<%= tweet.user.avatar_url %>">
            <span class="name"><%= tweet.user.name %></span> 
            @<%= tweet.user.username %> 
            <span class="time"><%= time_ago_in_words(tweet.created_at) %></span>
            <p> <%= tweet.content %> </p>
        </div>
    <% end %> 
    
</div>

<%= javascript_include_tag 'tweets' %>